### ISSUE TITLE
Use docker volumes for docker-compose

### ISSUE THREAD

**Issue by mathiashoeld** [openkfw/TruBudget#186]
We are currently mounting paths like `/tmp/bcMasterVolume` to the docker containers. This is dangerous for production setups, as the `/tmp` folder is deleted after reboot on Unix machines. 

Proposed solution: Use [docker volumes](https://docs.docker.com/storage/volumes/). Example for the docker-compose file: 

```
...
master:
    build:
      context: ../../blockchain
    environment:
      RPC_PORT: ${RPC_PORT}
      ORGANIZATION: ${ORGANIZATION}
      EXTERNAL_IP: ${EXTERNAL_IP}
    volumes:
      - masterVolume:/root/.multichain
    ports:
      - "7447:7447"
...

volumes:
   masterVolume:
```
